---
title: "Previous Editions"
---

Our conference has a rich history of bringing together the brightest minds in economics. Below you can explore our past editions, including highlights, notable speakers, and programs.

## [2025 Edition](2025-edition.qmd)

**Theme:** "Economic Development and Climate Change"  
**Date:** October 30-21, 2025  
**Location:** Paññāsāstra University of Cambodia, Siem Reap Campus (PUCSR), Siem Reap, Cambodia  
**Participants:** 70+ attendees from 12 countries

### Highlights

- Keynote speaker by Mr. Shakeel Ahmad (UNDP Cambodia), Prof. Sovannroeun Samreth (Saitama University), Prof. Phanith Chou (Royal University of Phnom Penh), Dr. Ratha Chiv (aññāsāstra University of Cambodia, Siem Reap Campus), and Prof. Olivier Bargain (Bordeaux University), Dr. Maria C. Lo Bue (University of Trieste), Dr. Rada Khoy (UNDP Cambodia), Dr. Daniel Yonto (Xi’an Jiaotong-Liverpool University), and Mr. Theara Khoun (UNDP Cambodia)

### Program

The program for the 2025 conference is available as a PDF file [here](files/saerd25_program.pdf).

## [2024 Edition](2024-edition.qmd)

**Theme:** "Economic Development and Climate Change"  
**Date:** August 15-16, 2024  
**Location:** Paññāsāstra University of Cambodia, Siem Reap Campus (PUCSR), Siem Reap, Cambodia  
**Participants:** 50+ attendees from 12 countries

### Highlights

- Keynote by Prof. Sovannroeun Samreth (Saitama University), Dr. Chandarany Ouch (The United Nations), Phanith Chou (Royal University of Phnom Penh), Dr. Dina Chhorn (Cambodia Development Resource), and Dr. Alexandre Reichart (Renmin University of China)
- Writing an edited book on *The Political Economy of the Asian Developing Regions*.

### Program

The program for the 2024 conference is available as a PDF file [here](files/saerd24_program.pdf).



## [2023 Edition](2023-edition.qmd)

**Theme:** "History of Economic Thought"  
**Date:** December 15-16, 2023  
**Location:** Royal University of Law and Economics, Phnom Penh, Cambodia  
**Participants:** 50+ attendees from 15 countries

### Highlights

- Keynote by Prof. Rebeca Gomez Betancourt (Université Lumière Lyon 2), Prof. Fabio Masini (Roma Tre University), Assoc. Prof. Alexandre Reichart (Renmin University of China), Dr. Danilo Spinola (Birmingham City University), Prof. Arpan Ganguly (FLAME University), Dr. Phal Chea (Cambodia Development Resource Institute), Dr. Phanith Chou (Royal University of Phnom Penh), and Prof. Raymond Leos (American University of Phnom Penh)

### Program

The program for the 2023 conference is available as a PDF file [here](files/agendaSAERD23.pdf).
